### ISSUE TITLE
Question about skip-tipping on reader stripe

### ISSUE THREAD

**Issue by obada15** [awazgyawali/flutter_stripe_terminal#4]
Hello ,

I want to ask you a question please,

I am working on using Stripe Reader M2 In flutter using your library (stripe_terminal) everything is fine but I am unable to do skip tipping because it is not supported in your library Do you have a solution to this issue or another way to remove the tips.

Thank you very much ..

Skip-tipping in documentation:

https://stripe.com/docs/terminal/features/collecting-tips/on-reader#skip-tipping

**Comment by awazgyawali** [comment]
@obada15 THis must be fixed on version 1.3.2.

**Comment by obada15** [comment]
thanx for you for your replay , I am obliged to find a quick solution because the project is suspended. please 
Can you tell me the expected time period for the release of the new version of the package?

**Comment by awazgyawali** [comment]
It's already released.

**Comment by obada15** [comment]
in this version stripe_terminal 1.3.2  the you added skip tipping ??

**Comment by obada15** [comment]
Thank you, I updated the package but when I insert the card it still asks me to insert it a second time to pull out the tips, and the response on stripe dashboard is " The customer has not entered their payment method."
please can you check it another time
